### PR TITLE
add page of 20231022 pydoc-zhtw meetup

### PR DESCRIPTION
**Pull request by mindihx**
preview: https://deploy-preview-262--swportal.netlify.app/meetup/2023/1022-pydoc

* kktix link is not ready yet

### CODE REVIEW

**Comment by yungyuc** [comment]
There is a scisprint planned on 10/21.  @kuomc could you please help align?  It's hard to promote two sprints happening at different places on the same day.

**Comment by yungyuc** [comment]
@mindihx please chime in in the discussion at https://discord.com/channels/730297880140578906/1007075707400237067/1156050423598297138

**Comment by kuomc** [comment]
I saw the discussion in discord about date. Please update the date.

**Comment by mindihx** [comment]
> I saw the discussion in discord about date. Please update the date.

date updated, thanks!

**Comment by yungyuc** [comment]
@kuomc Could you please process it?

**Review by kuomc — COMMENTED** [review]
I will publish the page. The kktix page can be finished later.

**Pull request merged**
