### PR TITLE
fix <li> indentation

### PR DESCRIPTION
**Pull request by terrychan999**

### CODE REVIEW

**Comment by yungyuc** [comment]
Thanks @terrychan999 .

@chestercheng IIRC we used tailwind to generate the css?  If we manually modify the style file, would it conflict with tailwind?

If it conflicts, what would we like to do?  I can think of two possibilities: (i) give up tailwind and maintain style sheets manually and (ii) use tailwind to make the style change.

**Comment by terrychan999** [comment]
`main.css` is actually generated by tailwind.

Because from the Makefile I notice `make deploy` doesn't trigger `make css` to invoke tailwind,
so I use `make css` to generate it.

**Comment by yungyuc** [comment]
I missed `main.css` in the first place.  Is it necessary to do the generation in this PR?  If not, is it possible to only update `styles.css`?  Diff on `main.css` is so large.  It is 6xk lines of code.

**Comment by chestercheng** [comment]
It's my fault, the `main.css` should not pushed into this repo...

**Comment by yungyuc** [comment]
> It's my fault, the `main.css` should not pushed into this repo...

If it is not in the repository, would tailwind be a dependency when we build the repo locally?

I do not have tailwind installed.  If tailwind becomes a dependency, I need to learn how to install it and I think it should be documented somewhere in the repo.

Let us give it more discussions before jumping to a conclusion.

**Comment by terrychan999** [comment]
> If it is not in the repository, would tailwind be a dependency...

Yes, npx (npm package executor)(bundled with Node.js) will then become a dependency to build tailwind locally.

**Comment by yungyuc** [comment]
> > If it is not in the repository, would tailwind be a dependency...
> 
> Yes, npx (npm package executor)(bundled with Node.js) will then become a dependency to build tailwind locally.

Ok.  It seems to be clear that, in the time being, to update style sheets we need to update `main.css`.  Let's make the dependency on tailwind a separate issue.

I am merging this PR.  Thanks a lot @terrychan999 !

**Pull request merged**
