### PR TITLE
Add title link

### PR DESCRIPTION
**Pull request by chestercheng**
related: #6 #4

### CODE REVIEW

**Comment by yungyuc** [comment]
How large is the headerid plugin?  If it's not too big, I am thinking about copying it to the repo instead of using submodule.  It seems to me that submodule is much more unstable and hurts overall productivity.

**Review by yungyuc — COMMENTED** [review]
We should discuss the possibility of copying headerid plugin instead of git submodule.

**Comment by yungyuc** [comment]
In https://github.com/getpelican/pelican-plugins/tree/master/headerid, it seems that the plugin has not been changed for 3 years, and the size is tiny.  I'd say we should copy the plugin files instead of adding the complexity of git submodule to the build system.

**Comment by yungyuc** [comment]
@chestercheng On the plugin management, do you have any comments?

**Comment by chestercheng** [comment]
> @chestercheng On the plugin management, do you have any comments?

Since the plugin size is tiny and the repo is inactive, I think copying plugin instead is a good way.

On #4 "cherry-picking system" is meaning just copy necessary plugins from pelican-plugins, right?

**Comment by yungyuc** [comment]
> > @chestercheng On the plugin management, do you have any comments?
> 
> Since the plugin size is tiny and the repo is inactive, I think copying plugin instead is a good way.
> 
> On #4 "cherry-picking system" is meaning just copy necessary plugins from pelican-plugins, right?

Yes.  I think copying the necessary plugins here is good.

**Comment by yungyuc** [comment]
Looks good.  Thanks a lot.

**Pull request merged**
