### PR TITLE
feat(content/project): add pydoc-zhtw to project list

### PR DESCRIPTION
**Pull request by mattwang44**
preview:
image

### CODE REVIEW

**Comment by yungyuc** [comment]
An screenshot for review is neat.  We should encourage future contributor to do the same.  And / or we can add the link to the netlify PR deployment page like: https://deploy-preview-218--swportal.netlify.app/project

**Comment by yungyuc** [comment]
@cstnaya Could you please take a look and comment?  Thanks.

**Comment by cstnaya** [comment]
> 
> preview:
> image
> 

It looks great to me. 😄

**Comment by yungyuc** [comment]
Wonderful.  @cstnaya , could you please proceed to merge and publish it?  Please consult the README for the process.  If you have any questions, please ping us here or on the discord.

**Review by cstnaya — COMMENTED** [review]
Looks great to me! :)

**Comment by yungyuc** [comment]
Thanks, @cstnaya .  You need another PR to publish it to the main site from `develop` branch.

**Pull request merged**
