### PR TITLE
[event] 2021-05end placeholder (no venue yet)

### PR DESCRIPTION
**Pull request by yungyuc**
@tigercosmos we will use github for the website (at https://sciwork.dev/) to announce the sprints.  We will need your help for venue and logistics.

### CODE REVIEW

**Comment by yungyuc** [comment]
@chestercheng I am creating this placeholder.  I think we can publish it.  But before the RSVP page and venue are ready, we don't put it in the sprint list page.  How do you think?

**Comment by chestercheng** [comment]
@yungyuc we can add some tag (e.g. planning) on this event and still put it in the sprint list, i think it makes audiences easy to know the upcoming events. as a result, they may keep eyes on this website

**Comment by yungyuc** [comment]
> @yungyuc we can add some tag (e.g. planning) on this event and still put it in the sprint list, i think it makes audiences easy to know the upcoming events. as a result, they may keep eyes on this website

Good idea.  I added the event to the list with the `[Planning]` tag with https://github.com/sciwork/swportal/pull/59/commits/c2c865cc1bbbc97107c5f60dd4ed1988120c120b .  How does it look?

**Comment by chestercheng** [comment]
LGTM. I'll publish it later.

**Pull request merged**
