### PR TITLE
Update project list and registration link for November Hsinchu sprint

### PR DESCRIPTION
**Pull request by meng5113**
The PR is to update project list and registration link for November Hsinchu sprint

### CODE REVIEW

**Comment by YenPeiChen07** [comment]
@chestercheng, the CI seems to be failed, could you please help to check it out?

**Comment by chestercheng** [comment]
@meng5113 #491 is a workaround for the CI issue. Please rebase your branch

**Comment by meng5113** [comment]
Hi @YenPeiChen07 I’ve rebased my branch. Please take a look. Thanks!

**Review by YenPeiChen07 — APPROVED** [review]
Thanks, @meng5113. It looks great to me.

**Pull request merged**
